esrlabs/jay_api

.github/workflows/release.yml
lib/jay_api/elasticsearch/client.rb

This Github action runs whenever a Pull Request that changes the `lib/jay_api/version.rb` file is merged.
It builds the gem, creates a release (with a corresponding tag) and pushes the generated gem package to rubygems.org. It uses Rubygems's trusted publishers system hence there is no need for an OTP code.

[JAY-591] Add Github action for releasing the gem

---

CHANGELOG.md
documentation/source/user_guidelines/elasticsearch/aggregations.rst
lib/jay_api/elasticsearch/query_builder/aggregations.rb
lib/jay_api/elasticsearch/query_builder/aggregations/max.rb
spec/jay_api/elasticsearch/query_builder/aggregations/max_spec.rb
spec/jay_api/elasticsearch/query_builder/aggregations_spec.rb

The added 'Max' aggregation is of a metric type which allows to sort other aggregations based on custom
'Max' aggregations. The following is a concrete example of an aggregation that requires a 'Max' aggregation:
```
{
aggs: {
sut_revisions: {
terms: {
field: "sut_revision.keyword",
size: 100,
order: { timestamp: "desc" }
},
aggs: {
timestamp: {
max: {
field: "scope.exported_at"
}
}
}
}
}
}
```
Note that this will return the different 'sut_revision's ordered by the 'exported_at' timestamp.

Add Elasticsearch 'Max' aggregation

---

lib/jay_api.rb
lib/jay_api/elasticsearch.rb
lib/jay_api/elasticsearch/errors.rb
lib/jay_api/elasticsearch/query_builder.rb
lib/jay_api/elasticsearch/query_builder/errors.rb

Without these in place some of the Elasticsearch related classes did not get loaded when the console was invoked.
Having these in place also ensures an accurate code-coverage report since the files will be loaded even if they are never explicitly loaded by the tests, hence showing up as not covered in the report.

Add missing Elasticsearch modules and requires

---

CHANGELOG.md
documentation/source/user_guidelines/elasticsearch/query_builder.rst
lib/jay_api/elasticsearch/query_builder.rb
spec/jay_api/elasticsearch/query_builder_spec.rb

Change the `QueryBuilder#source` method to allow `filter_expr` to take `false`, arrays and hashes in addition to simple strings.
The main driver behind this change is allowing the use of `false` to remove the document's source from the result JSON. `Array` and `Hash` are being added in order to match the method's implementation to Elasticsearch's documentation.

[JAY-495] Allow QueryBuilder#source to take false, arrays and hashes

---

CHANGELOG.md
lib/jay_api/version.rb

In this version:
- `QueryBuilder#source` can now take `false`, `Array` and `Hash` in addition to simple strings.

[RELEASE] Version 27.2.0

---

CHANGELOG.md
lib/jay_api/properties_fetcher.rb
spec/jay_api/properties_fetcher_spec.rb

PropertiesFetcher#last was sorting the records in descending order and then taking the last one, effectively meaning that it returned the first one.
This change fixes the issue by sorting the records in ascending order instead.

[JAY-639] Fix PropertiesFetcher#last

---

CHANGELOG.md
lib/jay_api/version.rb

- `PropertiesFetcher#last` now correctly returns the last set of properties
(ordered chronologically).

[RELEASE] Version 27.2.1

---

CHANGELOG.md
documentation/source/user_guidelines/elasticsearch/aggregations.rst
lib/jay_api/elasticsearch/query_builder/aggregations.rb
lib/jay_api/elasticsearch/query_builder/aggregations/cardinality.rb
spec/jay_api/elasticsearch/query_builder/aggregations/cardinality_spec.rb
spec/jay_api/elasticsearch/query_builder/aggregations_spec.rb

The Cardinality aggregation counts the **approximate** number of unique values that a field has in the index.
The changes in this Pull Request add the `Aggregations::Cardinality` class, the `Aggregations#cardinality` method and the documentation for the newly added feature.

[JAY-625] Add the Cardinality aggregation for Elasticsearch

---

CHANGELOG.md
lib/jay_api/version.rb

- The `Aggregations::Cardinality` class and the `Aggregations#cardinality`
method. They make it possible to use Elasticsearch's `cardinality`
aggregations.
- `GitilesHelper#gitiles_url` can now be called without a `path`. When no path
is given the method generates a link to the given `refspec` instead.

[RELEASE] Version 27.3.0

---

CHANGELOG.md
lib/jay_api/elasticsearch/client.rb
spec/integration/jay_api/elasticsearch/client_spec.rb

The method allows the user to ping the Elasticsearch cluster to check connectivity and latency, without the need for any previous knowledge about the cluster, like endpoint or index names.
The method just forwards the call to the underlying Elasticsearch Transport Client's `#ping` method. Which returns `true` when the ping is successful and `false` when it fails. Although, less common, it can also raise a `Transport::Errors::Forbidden` when the user doesn't have permissions to ping the cluster.

[JAY-409] Add #ping to Elasticsearch::Client

---

lib/jay_api/elasticsearch/query_builder/aggregations/date_histogram.rb
spec/jay_api/elasticsearch/query_builder/aggregations/date_histogram_spec.rb

The hash generated by the method was missing the `date_histogram` key. The keys were instead being added directly to the top-level hash.

[BUGFIX] Fix a bug in DateHistogram#to_h

---

CHANGELOG.md
lib/jay_api/version.rb

- The `Aggregations::DateHistogram` class and the `Aggregations#date_histogram`
method. They make it possible to use Elasticsearch's `date_histogram`
aggregations.

[RELEASE] Version 27.5.0

---

CHANGELOG.md
lib/jay_api/version.rb

This contains a fix to the cloning of the TopHits aggregation.

[RELEASE] Version 27.5.1

---

spec/jay_api/configuration_spec.rb

The tests of the method were improperly nested inside the tests for the method `#deep_to_h`. This commit fixes the issue by bringing them out.

Fix the nesting of the Configuration#to_yaml tests

---

lib/jay_api/configuration.rb

RuboCop suggested using `#transform_values` instead of `#to_h`. This commit applies said suggestion.

Fix RuboCop warning in Configuration#value_for_h

---

CHANGELOG.md
lib/jay_api/configuration.rb
spec/jay_api/configuration_spec.rb

The method allows the caller to get the list of keys that the configuration object has. This could be used to iterate over the elements in the `Configuration` object or to validate the object's structure without having to turn it into a Hash first (`#to_h`).
Note that the addition of this method means that it is no longer possible to access the value of a an attribute called `keys` via the dot syntax, however, it is still possible to access its value using the brackets: `[]`

[JAY-653] Add Configuration#keys

---

CHANGELOG.md
documentation/source/user_guidelines/elasticsearch/stats.rst
lib/jay_api/elasticsearch.rb
lib/jay_api/elasticsearch/client.rb
lib/jay_api/elasticsearch/stats.rb
lib/jay_api/elasticsearch/stats/index.rb
lib/jay_api/elasticsearch/stats/indices.rb
spec/integration/jay_api/elasticsearch/client_spec.rb
spec/jay_api/elasticsearch/stats/index_spec.rb
spec/jay_api/elasticsearch/stats/indices_spec.rb
spec/jay_api/elasticsearch/stats_spec.rb

This Pull Request adds a set of classes and method to allow the user to get statistics about the Elasticsearch cluster.
The main entry point is the `Elasticsearch::Stats` class, which can be retrieved by calling the `#stats` method on an instance of the `Elasticsearch::Client` class. For the moment only one method is available: `#indices`, which gives access to the index-related statistics of the cluster.
At the moment this can only be used to enumerate the indices, making the distinction between system (starting with `.`) and user-created indices.
For the task that triggered these changes all that is needed is the number of user-created indices on the cluster, so the implementation includes only the bare-minimum changes needed to achieve that objective. More features will be added in the …

[JAY-655] Add a way to get statistics about the Elasticsearch cluster

---

CHANGELOG.md
lib/jay_api/version.rb

- The `#stats` method to the `Elasticsearch::Client` class. The method returns
an object that can be used to retrieve statistics about the Cluster. For the
moment only `#indices` is available, which returns index-related statistics.

[RELEASE] Version 28.1.0

---

CHANGELOG.md
documentation/source/user_guidelines/elasticsearch/stats.rst
lib/jay_api/elasticsearch/stats.rb
lib/jay_api/elasticsearch/stats/errors/stats_data_not_available.rb
lib/jay_api/elasticsearch/stats/node.rb
lib/jay_api/elasticsearch/stats/node/storage.rb
lib/jay_api/elasticsearch/stats/nodes.rb
spec/jay_api/elasticsearch/stats/node/storage_spec.rb
spec/jay_api/elasticsearch/stats/node_spec.rb
spec/jay_api/elasticsearch/stats/nodes_spec.rb
spec/jay_api/elasticsearch/stats_spec.rb

This pull request adds the necessary classes to allow the user to access the Elasticsearch cluster's node-related statistics. For the moment only information about the nodes' storage can be accessed. More information will probably be accessible in the future.
The `Storage` class has ben equipped with a `+` operator in order to allow clients to easily calculate the total storage on the cluster, by adding together the storage data for each of the nodes.

[JAY-656] Add a way to access the Elasticsearch cluster's node-related statistics

---

CHANGELOG.md
documentation/source/user_guidelines/elasticsearch/aggregations.rst
lib/jay_api/elasticsearch/query_builder/aggregations.rb
lib/jay_api/elasticsearch/query_builder/aggregations/composite.rb
lib/jay_api/elasticsearch/query_builder/aggregations/sources/sources.rb
lib/jay_api/elasticsearch/query_builder/aggregations/sources/terms.rb
spec/integration/jay_api/elasticsearch/query_builder/aggregations/composite_spec.rb
spec/jay_api/elasticsearch/query_builder/aggregations/composite_spec.rb
spec/jay_api/elasticsearch/query_builder/aggregations/sources/sources_spec.rb
spec/jay_api/elasticsearch/query_builder/aggregations/sources/terms_spec.rb

This type of aggregation allows documents to be aggregated using composite values made out of all the existing combinations of values coming from the specified sources. For the task that triggered the creation of these changes only the `terms` source is needed, hence that is the only source being added here.
When used with the `terms` source, the composite aggregation creates a bucket for each existing combination of values in the given fields.

[JAY-625] Add Elasticsearch's composite aggregation

---

CHANGELOG.md
lib/jay_api/version.rb

- The `Elasticsearch::Indexes` class. A class which allows multiple indexes to
be used (fed or queried) at the same time.

[RELEASE] Version 28.4.0

---

CHANGELOG.md
lib/jay_api/version.rb

- Updated the `git` dependency from `~> 1, >= 1.8.0-1` to `~> 3`.
- Increased the minimum Ruby version requirement to 3.1.0

[RELEASE] Version 29.0.0
